// Code generated by ent, DO NOT EDIT.

package registeredprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/clpombo/search/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLTE(FieldID, id))
}

// ParticipantName applies equality check predicate on the "participant_name" field. It's identical to ParticipantNameEQ.
func ParticipantName(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldParticipantName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// ParticipantNameEQ applies the EQ predicate on the "participant_name" field.
func ParticipantNameEQ(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldParticipantName, v))
}

// ParticipantNameNEQ applies the NEQ predicate on the "participant_name" field.
func ParticipantNameNEQ(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNEQ(FieldParticipantName, v))
}

// ParticipantNameIn applies the In predicate on the "participant_name" field.
func ParticipantNameIn(vs ...string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldIn(FieldParticipantName, vs...))
}

// ParticipantNameNotIn applies the NotIn predicate on the "participant_name" field.
func ParticipantNameNotIn(vs ...string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNotIn(FieldParticipantName, vs...))
}

// ParticipantNameGT applies the GT predicate on the "participant_name" field.
func ParticipantNameGT(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGT(FieldParticipantName, v))
}

// ParticipantNameGTE applies the GTE predicate on the "participant_name" field.
func ParticipantNameGTE(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGTE(FieldParticipantName, v))
}

// ParticipantNameLT applies the LT predicate on the "participant_name" field.
func ParticipantNameLT(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLT(FieldParticipantName, v))
}

// ParticipantNameLTE applies the LTE predicate on the "participant_name" field.
func ParticipantNameLTE(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLTE(FieldParticipantName, v))
}

// ParticipantNameContains applies the Contains predicate on the "participant_name" field.
func ParticipantNameContains(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldContains(FieldParticipantName, v))
}

// ParticipantNameHasPrefix applies the HasPrefix predicate on the "participant_name" field.
func ParticipantNameHasPrefix(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldHasPrefix(FieldParticipantName, v))
}

// ParticipantNameHasSuffix applies the HasSuffix predicate on the "participant_name" field.
func ParticipantNameHasSuffix(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldHasSuffix(FieldParticipantName, v))
}

// ParticipantNameEqualFold applies the EqualFold predicate on the "participant_name" field.
func ParticipantNameEqualFold(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEqualFold(FieldParticipantName, v))
}

// ParticipantNameContainsFold applies the ContainsFold predicate on the "participant_name" field.
func ParticipantNameContainsFold(v string) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldContainsFold(FieldParticipantName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasContract applies the HasEdge predicate on the "contract" edge.
func HasContract() predicate.RegisteredProvider {
	return predicate.RegisteredProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ContractTable, ContractColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContractWith applies the HasEdge predicate on the "contract" edge with a given conditions (other predicates).
func HasContractWith(preds ...predicate.RegisteredContract) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(func(s *sql.Selector) {
		step := newContractStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RegisteredProvider) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RegisteredProvider) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RegisteredProvider) predicate.RegisteredProvider {
	return predicate.RegisteredProvider(func(s *sql.Selector) {
		p(s.Not())
	})
}
