// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	InitiateChannel(ctx context.Context, in *Contract, opts ...grpc.CallOption) (*ChannelCreation, error)
	RegisterProvider(ctx context.Context, in *Contract, opts ...grpc.CallOption) (*ProviderRegistration, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) InitiateChannel(ctx context.Context, in *Contract, opts ...grpc.CallOption) (*ChannelCreation, error) {
	out := new(ChannelCreation)
	err := c.cc.Invoke(ctx, "/protobuf.Broker/InitiateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) RegisterProvider(ctx context.Context, in *Contract, opts ...grpc.CallOption) (*ProviderRegistration, error) {
	out := new(ProviderRegistration)
	err := c.cc.Invoke(ctx, "/protobuf.Broker/RegisterProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	InitiateChannel(context.Context, *Contract) (*ChannelCreation, error)
	RegisterProvider(context.Context, *Contract) (*ProviderRegistration, error)
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (*UnimplementedBrokerServer) InitiateChannel(context.Context, *Contract) (*ChannelCreation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateChannel not implemented")
}
func (*UnimplementedBrokerServer) RegisterProvider(context.Context, *Contract) (*ProviderRegistration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProvider not implemented")
}
func (*UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_InitiateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).InitiateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broker/InitiateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).InitiateChannel(ctx, req.(*Contract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_RegisterProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).RegisterProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broker/RegisterProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).RegisterProvider(ctx, req.(*Contract))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateChannel",
			Handler:    _Broker_InitiateChannel_Handler,
		},
		{
			MethodName: "RegisterProvider",
			Handler:    _Broker_RegisterProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/broker.proto",
}
