// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RegisteredContractsColumns holds the columns for the "registered_contracts" table.
	RegisteredContractsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "format", Type: field.TypeInt},
		{Name: "contract", Type: field.TypeBytes},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RegisteredContractsTable holds the schema information for the "registered_contracts" table.
	RegisteredContractsTable = &schema.Table{
		Name:       "registered_contracts",
		Columns:    RegisteredContractsColumns,
		PrimaryKey: []*schema.Column{RegisteredContractsColumns[0]},
	}
	// RegisteredProvidersColumns holds the columns for the "registered_providers" table.
	RegisteredProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "url", Type: field.TypeJSON},
		{Name: "participant_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "registered_contract_providers", Type: field.TypeString, Nullable: true, Size: 128},
	}
	// RegisteredProvidersTable holds the schema information for the "registered_providers" table.
	RegisteredProvidersTable = &schema.Table{
		Name:       "registered_providers",
		Columns:    RegisteredProvidersColumns,
		PrimaryKey: []*schema.Column{RegisteredProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "registered_providers_registered_contracts_providers",
				Columns:    []*schema.Column{RegisteredProvidersColumns[5]},
				RefColumns: []*schema.Column{RegisteredContractsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RegisteredContractsTable,
		RegisteredProvidersTable,
	}
)

func init() {
	RegisteredProvidersTable.ForeignKeys[0].RefTable = RegisteredContractsTable
}
