// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/clpombo/search/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/clpombo/search/ent/registeredcontract"
	"github.com/clpombo/search/ent/registeredprovider"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RegisteredContract is the client for interacting with the RegisteredContract builders.
	RegisteredContract *RegisteredContractClient
	// RegisteredProvider is the client for interacting with the RegisteredProvider builders.
	RegisteredProvider *RegisteredProviderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RegisteredContract = NewRegisteredContractClient(c.config)
	c.RegisteredProvider = NewRegisteredProviderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		RegisteredContract: NewRegisteredContractClient(cfg),
		RegisteredProvider: NewRegisteredProviderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		RegisteredContract: NewRegisteredContractClient(cfg),
		RegisteredProvider: NewRegisteredProviderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RegisteredContract.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RegisteredContract.Use(hooks...)
	c.RegisteredProvider.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.RegisteredContract.Intercept(interceptors...)
	c.RegisteredProvider.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RegisteredContractMutation:
		return c.RegisteredContract.mutate(ctx, m)
	case *RegisteredProviderMutation:
		return c.RegisteredProvider.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RegisteredContractClient is a client for the RegisteredContract schema.
type RegisteredContractClient struct {
	config
}

// NewRegisteredContractClient returns a client for the RegisteredContract from the given config.
func NewRegisteredContractClient(c config) *RegisteredContractClient {
	return &RegisteredContractClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `registeredcontract.Hooks(f(g(h())))`.
func (c *RegisteredContractClient) Use(hooks ...Hook) {
	c.hooks.RegisteredContract = append(c.hooks.RegisteredContract, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `registeredcontract.Intercept(f(g(h())))`.
func (c *RegisteredContractClient) Intercept(interceptors ...Interceptor) {
	c.inters.RegisteredContract = append(c.inters.RegisteredContract, interceptors...)
}

// Create returns a builder for creating a RegisteredContract entity.
func (c *RegisteredContractClient) Create() *RegisteredContractCreate {
	mutation := newRegisteredContractMutation(c.config, OpCreate)
	return &RegisteredContractCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RegisteredContract entities.
func (c *RegisteredContractClient) CreateBulk(builders ...*RegisteredContractCreate) *RegisteredContractCreateBulk {
	return &RegisteredContractCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RegisteredContract.
func (c *RegisteredContractClient) Update() *RegisteredContractUpdate {
	mutation := newRegisteredContractMutation(c.config, OpUpdate)
	return &RegisteredContractUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RegisteredContractClient) UpdateOne(rc *RegisteredContract) *RegisteredContractUpdateOne {
	mutation := newRegisteredContractMutation(c.config, OpUpdateOne, withRegisteredContract(rc))
	return &RegisteredContractUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RegisteredContractClient) UpdateOneID(id string) *RegisteredContractUpdateOne {
	mutation := newRegisteredContractMutation(c.config, OpUpdateOne, withRegisteredContractID(id))
	return &RegisteredContractUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RegisteredContract.
func (c *RegisteredContractClient) Delete() *RegisteredContractDelete {
	mutation := newRegisteredContractMutation(c.config, OpDelete)
	return &RegisteredContractDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RegisteredContractClient) DeleteOne(rc *RegisteredContract) *RegisteredContractDeleteOne {
	return c.DeleteOneID(rc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RegisteredContractClient) DeleteOneID(id string) *RegisteredContractDeleteOne {
	builder := c.Delete().Where(registeredcontract.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RegisteredContractDeleteOne{builder}
}

// Query returns a query builder for RegisteredContract.
func (c *RegisteredContractClient) Query() *RegisteredContractQuery {
	return &RegisteredContractQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRegisteredContract},
		inters: c.Interceptors(),
	}
}

// Get returns a RegisteredContract entity by its id.
func (c *RegisteredContractClient) Get(ctx context.Context, id string) (*RegisteredContract, error) {
	return c.Query().Where(registeredcontract.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RegisteredContractClient) GetX(ctx context.Context, id string) *RegisteredContract {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProviders queries the providers edge of a RegisteredContract.
func (c *RegisteredContractClient) QueryProviders(rc *RegisteredContract) *RegisteredProviderQuery {
	query := (&RegisteredProviderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(registeredcontract.Table, registeredcontract.FieldID, id),
			sqlgraph.To(registeredprovider.Table, registeredprovider.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, registeredcontract.ProvidersTable, registeredcontract.ProvidersColumn),
		)
		fromV = sqlgraph.Neighbors(rc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RegisteredContractClient) Hooks() []Hook {
	return c.hooks.RegisteredContract
}

// Interceptors returns the client interceptors.
func (c *RegisteredContractClient) Interceptors() []Interceptor {
	return c.inters.RegisteredContract
}

func (c *RegisteredContractClient) mutate(ctx context.Context, m *RegisteredContractMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RegisteredContractCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RegisteredContractUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RegisteredContractUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RegisteredContractDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RegisteredContract mutation op: %q", m.Op())
	}
}

// RegisteredProviderClient is a client for the RegisteredProvider schema.
type RegisteredProviderClient struct {
	config
}

// NewRegisteredProviderClient returns a client for the RegisteredProvider from the given config.
func NewRegisteredProviderClient(c config) *RegisteredProviderClient {
	return &RegisteredProviderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `registeredprovider.Hooks(f(g(h())))`.
func (c *RegisteredProviderClient) Use(hooks ...Hook) {
	c.hooks.RegisteredProvider = append(c.hooks.RegisteredProvider, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `registeredprovider.Intercept(f(g(h())))`.
func (c *RegisteredProviderClient) Intercept(interceptors ...Interceptor) {
	c.inters.RegisteredProvider = append(c.inters.RegisteredProvider, interceptors...)
}

// Create returns a builder for creating a RegisteredProvider entity.
func (c *RegisteredProviderClient) Create() *RegisteredProviderCreate {
	mutation := newRegisteredProviderMutation(c.config, OpCreate)
	return &RegisteredProviderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RegisteredProvider entities.
func (c *RegisteredProviderClient) CreateBulk(builders ...*RegisteredProviderCreate) *RegisteredProviderCreateBulk {
	return &RegisteredProviderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RegisteredProvider.
func (c *RegisteredProviderClient) Update() *RegisteredProviderUpdate {
	mutation := newRegisteredProviderMutation(c.config, OpUpdate)
	return &RegisteredProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RegisteredProviderClient) UpdateOne(rp *RegisteredProvider) *RegisteredProviderUpdateOne {
	mutation := newRegisteredProviderMutation(c.config, OpUpdateOne, withRegisteredProvider(rp))
	return &RegisteredProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RegisteredProviderClient) UpdateOneID(id uuid.UUID) *RegisteredProviderUpdateOne {
	mutation := newRegisteredProviderMutation(c.config, OpUpdateOne, withRegisteredProviderID(id))
	return &RegisteredProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RegisteredProvider.
func (c *RegisteredProviderClient) Delete() *RegisteredProviderDelete {
	mutation := newRegisteredProviderMutation(c.config, OpDelete)
	return &RegisteredProviderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RegisteredProviderClient) DeleteOne(rp *RegisteredProvider) *RegisteredProviderDeleteOne {
	return c.DeleteOneID(rp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RegisteredProviderClient) DeleteOneID(id uuid.UUID) *RegisteredProviderDeleteOne {
	builder := c.Delete().Where(registeredprovider.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RegisteredProviderDeleteOne{builder}
}

// Query returns a query builder for RegisteredProvider.
func (c *RegisteredProviderClient) Query() *RegisteredProviderQuery {
	return &RegisteredProviderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRegisteredProvider},
		inters: c.Interceptors(),
	}
}

// Get returns a RegisteredProvider entity by its id.
func (c *RegisteredProviderClient) Get(ctx context.Context, id uuid.UUID) (*RegisteredProvider, error) {
	return c.Query().Where(registeredprovider.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RegisteredProviderClient) GetX(ctx context.Context, id uuid.UUID) *RegisteredProvider {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryContract queries the contract edge of a RegisteredProvider.
func (c *RegisteredProviderClient) QueryContract(rp *RegisteredProvider) *RegisteredContractQuery {
	query := (&RegisteredContractClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rp.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(registeredprovider.Table, registeredprovider.FieldID, id),
			sqlgraph.To(registeredcontract.Table, registeredcontract.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, registeredprovider.ContractTable, registeredprovider.ContractColumn),
		)
		fromV = sqlgraph.Neighbors(rp.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RegisteredProviderClient) Hooks() []Hook {
	return c.hooks.RegisteredProvider
}

// Interceptors returns the client interceptors.
func (c *RegisteredProviderClient) Interceptors() []Interceptor {
	return c.inters.RegisteredProvider
}

func (c *RegisteredProviderClient) mutate(ctx context.Context, m *RegisteredProviderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RegisteredProviderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RegisteredProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RegisteredProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RegisteredProviderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RegisteredProvider mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		RegisteredContract, RegisteredProvider []ent.Hook
	}
	inters struct {
		RegisteredContract, RegisteredProvider []ent.Interceptor
	}
)
