// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/clpombo/search/ent/compatibilityresult"
	"github.com/clpombo/search/ent/predicate"
	"github.com/clpombo/search/ent/registeredcontract"
)

// CompatibilityResultQuery is the builder for querying CompatibilityResult entities.
type CompatibilityResultQuery struct {
	config
	ctx                     *QueryContext
	order                   []compatibilityresult.OrderOption
	inters                  []Interceptor
	predicates              []predicate.CompatibilityResult
	withRequirementContract *RegisteredContractQuery
	withProviderContract    *RegisteredContractQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompatibilityResultQuery builder.
func (crq *CompatibilityResultQuery) Where(ps ...predicate.CompatibilityResult) *CompatibilityResultQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *CompatibilityResultQuery) Limit(limit int) *CompatibilityResultQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *CompatibilityResultQuery) Offset(offset int) *CompatibilityResultQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *CompatibilityResultQuery) Unique(unique bool) *CompatibilityResultQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *CompatibilityResultQuery) Order(o ...compatibilityresult.OrderOption) *CompatibilityResultQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QueryRequirementContract chains the current query on the "requirement_contract" edge.
func (crq *CompatibilityResultQuery) QueryRequirementContract() *RegisteredContractQuery {
	query := (&RegisteredContractClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(compatibilityresult.Table, compatibilityresult.FieldID, selector),
			sqlgraph.To(registeredcontract.Table, registeredcontract.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, compatibilityresult.RequirementContractTable, compatibilityresult.RequirementContractColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderContract chains the current query on the "provider_contract" edge.
func (crq *CompatibilityResultQuery) QueryProviderContract() *RegisteredContractQuery {
	query := (&RegisteredContractClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(compatibilityresult.Table, compatibilityresult.FieldID, selector),
			sqlgraph.To(registeredcontract.Table, registeredcontract.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, compatibilityresult.ProviderContractTable, compatibilityresult.ProviderContractColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CompatibilityResult entity from the query.
// Returns a *NotFoundError when no CompatibilityResult was found.
func (crq *CompatibilityResultQuery) First(ctx context.Context) (*CompatibilityResult, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{compatibilityresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *CompatibilityResultQuery) FirstX(ctx context.Context) *CompatibilityResult {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CompatibilityResult ID from the query.
// Returns a *NotFoundError when no CompatibilityResult ID was found.
func (crq *CompatibilityResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{compatibilityresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *CompatibilityResultQuery) FirstIDX(ctx context.Context) int {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CompatibilityResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CompatibilityResult entity is found.
// Returns a *NotFoundError when no CompatibilityResult entities are found.
func (crq *CompatibilityResultQuery) Only(ctx context.Context) (*CompatibilityResult, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{compatibilityresult.Label}
	default:
		return nil, &NotSingularError{compatibilityresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *CompatibilityResultQuery) OnlyX(ctx context.Context) *CompatibilityResult {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CompatibilityResult ID in the query.
// Returns a *NotSingularError when more than one CompatibilityResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *CompatibilityResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{compatibilityresult.Label}
	default:
		err = &NotSingularError{compatibilityresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *CompatibilityResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CompatibilityResults.
func (crq *CompatibilityResultQuery) All(ctx context.Context) ([]*CompatibilityResult, error) {
	ctx = setContextOp(ctx, crq.ctx, "All")
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CompatibilityResult, *CompatibilityResultQuery]()
	return withInterceptors[[]*CompatibilityResult](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *CompatibilityResultQuery) AllX(ctx context.Context) []*CompatibilityResult {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CompatibilityResult IDs.
func (crq *CompatibilityResultQuery) IDs(ctx context.Context) (ids []int, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, "IDs")
	if err = crq.Select(compatibilityresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *CompatibilityResultQuery) IDsX(ctx context.Context) []int {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *CompatibilityResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, "Count")
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*CompatibilityResultQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *CompatibilityResultQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *CompatibilityResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, "Exist")
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *CompatibilityResultQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompatibilityResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *CompatibilityResultQuery) Clone() *CompatibilityResultQuery {
	if crq == nil {
		return nil
	}
	return &CompatibilityResultQuery{
		config:                  crq.config,
		ctx:                     crq.ctx.Clone(),
		order:                   append([]compatibilityresult.OrderOption{}, crq.order...),
		inters:                  append([]Interceptor{}, crq.inters...),
		predicates:              append([]predicate.CompatibilityResult{}, crq.predicates...),
		withRequirementContract: crq.withRequirementContract.Clone(),
		withProviderContract:    crq.withProviderContract.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithRequirementContract tells the query-builder to eager-load the nodes that are connected to
// the "requirement_contract" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CompatibilityResultQuery) WithRequirementContract(opts ...func(*RegisteredContractQuery)) *CompatibilityResultQuery {
	query := (&RegisteredContractClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withRequirementContract = query
	return crq
}

// WithProviderContract tells the query-builder to eager-load the nodes that are connected to
// the "provider_contract" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CompatibilityResultQuery) WithProviderContract(opts ...func(*RegisteredContractQuery)) *CompatibilityResultQuery {
	query := (&RegisteredContractClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withProviderContract = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ReqContractID string `json:"req_contract_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CompatibilityResult.Query().
//		GroupBy(compatibilityresult.FieldReqContractID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *CompatibilityResultQuery) GroupBy(field string, fields ...string) *CompatibilityResultGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompatibilityResultGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = compatibilityresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ReqContractID string `json:"req_contract_id,omitempty"`
//	}
//
//	client.CompatibilityResult.Query().
//		Select(compatibilityresult.FieldReqContractID).
//		Scan(ctx, &v)
func (crq *CompatibilityResultQuery) Select(fields ...string) *CompatibilityResultSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &CompatibilityResultSelect{CompatibilityResultQuery: crq}
	sbuild.label = compatibilityresult.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompatibilityResultSelect configured with the given aggregations.
func (crq *CompatibilityResultQuery) Aggregate(fns ...AggregateFunc) *CompatibilityResultSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *CompatibilityResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !compatibilityresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *CompatibilityResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CompatibilityResult, error) {
	var (
		nodes       = []*CompatibilityResult{}
		_spec       = crq.querySpec()
		loadedTypes = [2]bool{
			crq.withRequirementContract != nil,
			crq.withProviderContract != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CompatibilityResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CompatibilityResult{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withRequirementContract; query != nil {
		if err := crq.loadRequirementContract(ctx, query, nodes, nil,
			func(n *CompatibilityResult, e *RegisteredContract) { n.Edges.RequirementContract = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withProviderContract; query != nil {
		if err := crq.loadProviderContract(ctx, query, nodes, nil,
			func(n *CompatibilityResult, e *RegisteredContract) { n.Edges.ProviderContract = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *CompatibilityResultQuery) loadRequirementContract(ctx context.Context, query *RegisteredContractQuery, nodes []*CompatibilityResult, init func(*CompatibilityResult), assign func(*CompatibilityResult, *RegisteredContract)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*CompatibilityResult)
	for i := range nodes {
		fk := nodes[i].ReqContractID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(registeredcontract.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "req_contract_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CompatibilityResultQuery) loadProviderContract(ctx context.Context, query *RegisteredContractQuery, nodes []*CompatibilityResult, init func(*CompatibilityResult), assign func(*CompatibilityResult, *RegisteredContract)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*CompatibilityResult)
	for i := range nodes {
		fk := nodes[i].ProvContractID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(registeredcontract.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "prov_contract_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crq *CompatibilityResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *CompatibilityResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(compatibilityresult.Table, compatibilityresult.Columns, sqlgraph.NewFieldSpec(compatibilityresult.FieldID, field.TypeInt))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, compatibilityresult.FieldID)
		for i := range fields {
			if fields[i] != compatibilityresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if crq.withRequirementContract != nil {
			_spec.Node.AddColumnOnce(compatibilityresult.FieldReqContractID)
		}
		if crq.withProviderContract != nil {
			_spec.Node.AddColumnOnce(compatibilityresult.FieldProvContractID)
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *CompatibilityResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(compatibilityresult.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = compatibilityresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CompatibilityResultGroupBy is the group-by builder for CompatibilityResult entities.
type CompatibilityResultGroupBy struct {
	selector
	build *CompatibilityResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *CompatibilityResultGroupBy) Aggregate(fns ...AggregateFunc) *CompatibilityResultGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *CompatibilityResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, "GroupBy")
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompatibilityResultQuery, *CompatibilityResultGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *CompatibilityResultGroupBy) sqlScan(ctx context.Context, root *CompatibilityResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompatibilityResultSelect is the builder for selecting fields of CompatibilityResult entities.
type CompatibilityResultSelect struct {
	*CompatibilityResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *CompatibilityResultSelect) Aggregate(fns ...AggregateFunc) *CompatibilityResultSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *CompatibilityResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, "Select")
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompatibilityResultQuery, *CompatibilityResultSelect](ctx, crs.CompatibilityResultQuery, crs, crs.inters, v)
}

func (crs *CompatibilityResultSelect) sqlScan(ctx context.Context, root *CompatibilityResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
