// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/clpombo/search/ent/predicate"
	"github.com/clpombo/search/ent/registeredcontract"
	"github.com/clpombo/search/ent/registeredprovider"
)

// RegisteredContractQuery is the builder for querying RegisteredContract entities.
type RegisteredContractQuery struct {
	config
	ctx           *QueryContext
	order         []registeredcontract.OrderOption
	inters        []Interceptor
	predicates    []predicate.RegisteredContract
	withProviders *RegisteredProviderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RegisteredContractQuery builder.
func (rcq *RegisteredContractQuery) Where(ps ...predicate.RegisteredContract) *RegisteredContractQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit the number of records to be returned by this query.
func (rcq *RegisteredContractQuery) Limit(limit int) *RegisteredContractQuery {
	rcq.ctx.Limit = &limit
	return rcq
}

// Offset to start from.
func (rcq *RegisteredContractQuery) Offset(offset int) *RegisteredContractQuery {
	rcq.ctx.Offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *RegisteredContractQuery) Unique(unique bool) *RegisteredContractQuery {
	rcq.ctx.Unique = &unique
	return rcq
}

// Order specifies how the records should be ordered.
func (rcq *RegisteredContractQuery) Order(o ...registeredcontract.OrderOption) *RegisteredContractQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// QueryProviders chains the current query on the "providers" edge.
func (rcq *RegisteredContractQuery) QueryProviders() *RegisteredProviderQuery {
	query := (&RegisteredProviderClient{config: rcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(registeredcontract.Table, registeredcontract.FieldID, selector),
			sqlgraph.To(registeredprovider.Table, registeredprovider.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, registeredcontract.ProvidersTable, registeredcontract.ProvidersColumn),
		)
		fromU = sqlgraph.SetNeighbors(rcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RegisteredContract entity from the query.
// Returns a *NotFoundError when no RegisteredContract was found.
func (rcq *RegisteredContractQuery) First(ctx context.Context) (*RegisteredContract, error) {
	nodes, err := rcq.Limit(1).All(setContextOp(ctx, rcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{registeredcontract.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *RegisteredContractQuery) FirstX(ctx context.Context) *RegisteredContract {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RegisteredContract ID from the query.
// Returns a *NotFoundError when no RegisteredContract ID was found.
func (rcq *RegisteredContractQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rcq.Limit(1).IDs(setContextOp(ctx, rcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{registeredcontract.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *RegisteredContractQuery) FirstIDX(ctx context.Context) string {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RegisteredContract entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RegisteredContract entity is found.
// Returns a *NotFoundError when no RegisteredContract entities are found.
func (rcq *RegisteredContractQuery) Only(ctx context.Context) (*RegisteredContract, error) {
	nodes, err := rcq.Limit(2).All(setContextOp(ctx, rcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{registeredcontract.Label}
	default:
		return nil, &NotSingularError{registeredcontract.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *RegisteredContractQuery) OnlyX(ctx context.Context) *RegisteredContract {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RegisteredContract ID in the query.
// Returns a *NotSingularError when more than one RegisteredContract ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *RegisteredContractQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rcq.Limit(2).IDs(setContextOp(ctx, rcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{registeredcontract.Label}
	default:
		err = &NotSingularError{registeredcontract.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *RegisteredContractQuery) OnlyIDX(ctx context.Context) string {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RegisteredContracts.
func (rcq *RegisteredContractQuery) All(ctx context.Context) ([]*RegisteredContract, error) {
	ctx = setContextOp(ctx, rcq.ctx, "All")
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RegisteredContract, *RegisteredContractQuery]()
	return withInterceptors[[]*RegisteredContract](ctx, rcq, qr, rcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rcq *RegisteredContractQuery) AllX(ctx context.Context) []*RegisteredContract {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RegisteredContract IDs.
func (rcq *RegisteredContractQuery) IDs(ctx context.Context) (ids []string, err error) {
	if rcq.ctx.Unique == nil && rcq.path != nil {
		rcq.Unique(true)
	}
	ctx = setContextOp(ctx, rcq.ctx, "IDs")
	if err = rcq.Select(registeredcontract.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *RegisteredContractQuery) IDsX(ctx context.Context) []string {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *RegisteredContractQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rcq.ctx, "Count")
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rcq, querierCount[*RegisteredContractQuery](), rcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *RegisteredContractQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *RegisteredContractQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rcq.ctx, "Exist")
	switch _, err := rcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *RegisteredContractQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RegisteredContractQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *RegisteredContractQuery) Clone() *RegisteredContractQuery {
	if rcq == nil {
		return nil
	}
	return &RegisteredContractQuery{
		config:        rcq.config,
		ctx:           rcq.ctx.Clone(),
		order:         append([]registeredcontract.OrderOption{}, rcq.order...),
		inters:        append([]Interceptor{}, rcq.inters...),
		predicates:    append([]predicate.RegisteredContract{}, rcq.predicates...),
		withProviders: rcq.withProviders.Clone(),
		// clone intermediate query.
		sql:  rcq.sql.Clone(),
		path: rcq.path,
	}
}

// WithProviders tells the query-builder to eager-load the nodes that are connected to
// the "providers" edge. The optional arguments are used to configure the query builder of the edge.
func (rcq *RegisteredContractQuery) WithProviders(opts ...func(*RegisteredProviderQuery)) *RegisteredContractQuery {
	query := (&RegisteredProviderClient{config: rcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rcq.withProviders = query
	return rcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Format int `json:"format,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RegisteredContract.Query().
//		GroupBy(registeredcontract.FieldFormat).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rcq *RegisteredContractQuery) GroupBy(field string, fields ...string) *RegisteredContractGroupBy {
	rcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RegisteredContractGroupBy{build: rcq}
	grbuild.flds = &rcq.ctx.Fields
	grbuild.label = registeredcontract.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Format int `json:"format,omitempty"`
//	}
//
//	client.RegisteredContract.Query().
//		Select(registeredcontract.FieldFormat).
//		Scan(ctx, &v)
func (rcq *RegisteredContractQuery) Select(fields ...string) *RegisteredContractSelect {
	rcq.ctx.Fields = append(rcq.ctx.Fields, fields...)
	sbuild := &RegisteredContractSelect{RegisteredContractQuery: rcq}
	sbuild.label = registeredcontract.Label
	sbuild.flds, sbuild.scan = &rcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RegisteredContractSelect configured with the given aggregations.
func (rcq *RegisteredContractQuery) Aggregate(fns ...AggregateFunc) *RegisteredContractSelect {
	return rcq.Select().Aggregate(fns...)
}

func (rcq *RegisteredContractQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rcq); err != nil {
				return err
			}
		}
	}
	for _, f := range rcq.ctx.Fields {
		if !registeredcontract.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	return nil
}

func (rcq *RegisteredContractQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RegisteredContract, error) {
	var (
		nodes       = []*RegisteredContract{}
		_spec       = rcq.querySpec()
		loadedTypes = [1]bool{
			rcq.withProviders != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RegisteredContract).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RegisteredContract{config: rcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rcq.withProviders; query != nil {
		if err := rcq.loadProviders(ctx, query, nodes,
			func(n *RegisteredContract) { n.Edges.Providers = []*RegisteredProvider{} },
			func(n *RegisteredContract, e *RegisteredProvider) { n.Edges.Providers = append(n.Edges.Providers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rcq *RegisteredContractQuery) loadProviders(ctx context.Context, query *RegisteredProviderQuery, nodes []*RegisteredContract, init func(*RegisteredContract), assign func(*RegisteredContract, *RegisteredProvider)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*RegisteredContract)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.RegisteredProvider(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(registeredcontract.ProvidersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.registered_contract_providers
		if fk == nil {
			return fmt.Errorf(`foreign-key "registered_contract_providers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "registered_contract_providers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rcq *RegisteredContractQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	_spec.Node.Columns = rcq.ctx.Fields
	if len(rcq.ctx.Fields) > 0 {
		_spec.Unique = rcq.ctx.Unique != nil && *rcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *RegisteredContractQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(registeredcontract.Table, registeredcontract.Columns, sqlgraph.NewFieldSpec(registeredcontract.FieldID, field.TypeString))
	_spec.From = rcq.sql
	if unique := rcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rcq.path != nil {
		_spec.Unique = true
	}
	if fields := rcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registeredcontract.FieldID)
		for i := range fields {
			if fields[i] != registeredcontract.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *RegisteredContractQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(registeredcontract.Table)
	columns := rcq.ctx.Fields
	if len(columns) == 0 {
		columns = registeredcontract.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.ctx.Unique != nil && *rcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RegisteredContractGroupBy is the group-by builder for RegisteredContract entities.
type RegisteredContractGroupBy struct {
	selector
	build *RegisteredContractQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *RegisteredContractGroupBy) Aggregate(fns ...AggregateFunc) *RegisteredContractGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the selector query and scans the result into the given value.
func (rcgb *RegisteredContractGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcgb.build.ctx, "GroupBy")
	if err := rcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RegisteredContractQuery, *RegisteredContractGroupBy](ctx, rcgb.build, rcgb, rcgb.build.inters, v)
}

func (rcgb *RegisteredContractGroupBy) sqlScan(ctx context.Context, root *RegisteredContractQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rcgb.flds)+len(rcgb.fns))
		for _, f := range *rcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RegisteredContractSelect is the builder for selecting fields of RegisteredContract entities.
type RegisteredContractSelect struct {
	*RegisteredContractQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rcs *RegisteredContractSelect) Aggregate(fns ...AggregateFunc) *RegisteredContractSelect {
	rcs.fns = append(rcs.fns, fns...)
	return rcs
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *RegisteredContractSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcs.ctx, "Select")
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RegisteredContractQuery, *RegisteredContractSelect](ctx, rcs.RegisteredContractQuery, rcs, rcs.inters, v)
}

func (rcs *RegisteredContractSelect) sqlScan(ctx context.Context, root *RegisteredContractQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rcs.fns))
	for _, fn := range rcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
