// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/clpombo/search/ent/registeredcontract"
	"github.com/clpombo/search/ent/registeredprovider"
	"github.com/clpombo/search/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	registeredcontractFields := schema.RegisteredContract{}.Fields()
	_ = registeredcontractFields
	// registeredcontractDescContract is the schema descriptor for contract field.
	registeredcontractDescContract := registeredcontractFields[2].Descriptor()
	// registeredcontract.ContractValidator is a validator for the "contract" field. It is called by the builders before save.
	registeredcontract.ContractValidator = registeredcontractDescContract.Validators[0].(func([]byte) error)
	// registeredcontractDescCreatedAt is the schema descriptor for created_at field.
	registeredcontractDescCreatedAt := registeredcontractFields[3].Descriptor()
	// registeredcontract.DefaultCreatedAt holds the default value on creation for the created_at field.
	registeredcontract.DefaultCreatedAt = registeredcontractDescCreatedAt.Default.(func() time.Time)
	// registeredcontractDescID is the schema descriptor for id field.
	registeredcontractDescID := registeredcontractFields[0].Descriptor()
	// registeredcontract.IDValidator is a validator for the "id" field. It is called by the builders before save.
	registeredcontract.IDValidator = func() func(string) error {
		validators := registeredcontractDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	registeredproviderFields := schema.RegisteredProvider{}.Fields()
	_ = registeredproviderFields
	// registeredproviderDescParticipantName is the schema descriptor for participant_name field.
	registeredproviderDescParticipantName := registeredproviderFields[2].Descriptor()
	// registeredprovider.ParticipantNameValidator is a validator for the "participant_name" field. It is called by the builders before save.
	registeredprovider.ParticipantNameValidator = registeredproviderDescParticipantName.Validators[0].(func(string) error)
	// registeredproviderDescCreatedAt is the schema descriptor for created_at field.
	registeredproviderDescCreatedAt := registeredproviderFields[3].Descriptor()
	// registeredprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	registeredprovider.DefaultCreatedAt = registeredproviderDescCreatedAt.Default.(func() time.Time)
	// registeredproviderDescUpdatedAt is the schema descriptor for updated_at field.
	registeredproviderDescUpdatedAt := registeredproviderFields[4].Descriptor()
	// registeredprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	registeredprovider.DefaultUpdatedAt = registeredproviderDescUpdatedAt.Default.(func() time.Time)
	// registeredprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	registeredprovider.UpdateDefaultUpdatedAt = registeredproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// registeredproviderDescID is the schema descriptor for id field.
	registeredproviderDescID := registeredproviderFields[0].Descriptor()
	// registeredprovider.DefaultID holds the default value on creation for the id field.
	registeredprovider.DefaultID = registeredproviderDescID.Default.(func() uuid.UUID)
}
