// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RegisteredContract is the predicate function for registeredcontract builders.
type RegisteredContract func(*sql.Selector)

// RegisteredProvider is the predicate function for registeredprovider builders.
type RegisteredProvider func(*sql.Selector)
